### PR TITLE
Shipping Cost

### LINKED ISSUE #146: Shipping charges are incorrect
If price >= 5000¥, delivery charge is free
if price < 5000¥, delivery charge = 500¥

This needs to be updated in the cart page.

### PR DESCRIPTION
**Pull request by DavidCuentasMar**
Fixes: #146 
Youtube Link: https://www.youtube.com/watch?v=QPTwpkCz9q8
Youtube Link (2): https://www.youtube.com/watch?v=Y6bxedUduOE
PD: minSdkVersion changed to solved problems with stripe lib

### CODE REVIEW

**Comment by dragonfly91** [comment]
@DavidCuentasMar The row highlighted in red (in below image) is the section for shipping charges. Can you please update this row to reflect the shipping cost?

if shipping cost = 0, display "送料無料" (the same text being displayed right now)
if shipping cost = x, display "x" (according to the same style as the sub total cost)

Screen Shot 2020-03-13 at 8 25 29

**Review by dragonfly91 — CHANGES_REQUESTED** [review]
Left a comment about display. Please address it!

**Comment by dragonfly91** [comment]
@DavidCuentasMar can you please post the updated demo video?

**Comment by DavidCuentasMar** [comment]
New Demo: https://www.youtube.com/watch?v=Y6bxedUduOE

**Review by dragonfly91 — APPROVED** [review]

**Pull request merged**
